apiVersion: skaffold/v4beta6
kind: Config
manifests:
  rawYaml:
  - ./infra/k8s/*
build:
  # local:
  # concurrency: 1
  # tryImportMissing: false
  # useDockerCLI: false
  # push: false
  googleCloudBuild:
    projectId: ticketing-dev-401715
  artifacts:
  - image: us.gcr.io/ticketing-dev-401715/auth
    context: auth
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - dest: .
        src: 'src/**/*.ts'
  - image: us.gcr.io/ticketing-dev-401715/client
    context: client
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - dest: .
        src: '**/*.js'
  - image: us.gcr.io/ticketing-dev-401715/common
    context: common
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - dest: .
        src: 'src/**/*.ts'
  - image: us.gcr.io/ticketing-dev-401715/orders
    context: orders
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - dest: .
        src: 'src/**/*.ts'
  - image: rallycoding/tickets
    context: tickets
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: 'src/**/*.ts'
        dest: .
  - image: rallycoding/orders
    context: orders
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: 'src/**/*.ts'
        dest: .
  - image: rallycoding/expiration
    context: expiration
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: 'src/**/*.ts'
        dest: .
  - image: rallycoding/payments
    context: payments
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: 'src/**/*.ts'
        dest: .

